//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisAlunos.ModelData.Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class Responsaveis
    {
        public int ResponsavelID { get; set; }
        public string Nome { get; set; }
        public string RG { get; set; }
        public string CPF { get; set; }
        public string Profissao { get; set; }
        public string Celular { get; set; }
        public System.DateTime DataCadastro { get; set; }
        public string TipoParentesco { get; set; }
        public int AlunoID { get; set; }
    
        public virtual Alunos Alunos { get; set; }
    }
}
