//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisAlunos.ModelData.Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int UsuarioID { get; set; }
        public string Nome { get; set; }
        public string CPF { get; set; }
        public string Sexo { get; set; }
        public System.DateTime DataCadastro { get; set; }
        public int CidadeID { get; set; }
        public string Email { get; set; }
        public string Senha { get; set; }
    
        public virtual Cidades Cidades { get; set; }
    }
}
